### ISSUE TITLE
Game dont load at all!

### ISSUE THREAD

**Issue by iBibek** [santiagoLabs/EEG-Brain-Computer-Interface-to-play-Pong#1]
Hello Author,
Thank you so much for creating the Cortex file, it helps a lot. 

The issue I am facing is that after finishing all the steps in the LAIN menu, the game doesn't start at all. Any idea on how  to resolve this? I am using the latest 3.8 python version.

**Comment by santiagoLabs** [comment]
Hey iBibek, really glad you find Cortex useful! 

The only instance in which the game wouldn't work is when the headset is not properly connected to LAIN. 
What errors are you getting when you're running the game?

**Comment by iBibek** [comment]
Hello,
Thanks for the reply.
I am well connected with the headset, all the steps in the LAIN menu go smoothly from checking the headset connection status to all the way to loading the profile. I also see the screen with 'You are all set to play the game', but the game window is plain blank.

**Comment by santiagoLabs** [comment]
Hey, Are you still using it?

**Comment by iBibek** [comment]
Yeah, I did use it but had to make many changes. 
Thank your for creating this repo, it really helped me :)
